version: "3.9"
services:
  api: 
    container_name: dev1
    build: ./dev1/
    ports: 
      - "5000:5000"
    volumes: 
      - type: volume
        source: dev1-vol
        target: /app 
  nodered:
    container_name: nodered
    build: ./nodered/
    ports:
      - "1880:1880"
    volumes:
      - type: volume
        source: nodered-vol
        target: /data
    environment:
      - INFLUXDB_TOKEN=pranavp2810token
  influxdb:
    container_name: influxdb
    build: ./influxdb/
    ports:
      - "8086:8086"
    volumes:
      - type: volume
        source: influxdb-vol
        target: /var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=pranavp2810
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345
      - DOCKER_INFLUXDB_INIT_ORG=ppp
      - DOCKER_INFLUXDB_INIT_BUCKET=pppbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=pranavp2810token
  grafana: 
    container_name: grafana
    image: grafana/grafana
    ports: 
      - "3000:3000"
    volumes: 
      - type: volume
        source: grafana-vol
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=pranavp2810
      - GF_SECURITY_ADMIN_PASSWORD=12345
volumes:
  dev1-vol: {}
  nodered-vol: {}
  influxdb-vol: {}
  grafana-vol: {}